spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://tripinmyroom-rds.csi3ui1uyurt.ap-northeast-2.rds.amazonaws.com:33060/tripinmyroom
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${RDB_USERNAME}
    password: ${RDB_PASSWORD}
